name: CI BookingApp

on:
  push:
    branches:
      - master  # Modifie 'main' en 'master' si ta branche principale s'appelle 'master'
  pull_request:
    branches:
      - master  # Assure-toi que le workflow s'exécute aussi lors d'un pull request vers master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]  # Ou 20, selon ta version de Node.js

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Backend (api)
    - name: Install backend dependencies
      working-directory: ./api
      run: npm install

    # Frontend (client)
    - name: Install client dependencies
      working-directory: ./client
      run: npm install

    - name: Fix permissions
      run: sudo chmod -R 755 .

    - name: Build client
      working-directory: ./client
      run: npm run build

    # Admin (admin)
    - name: Install admin dependencies
      working-directory: ./admin
      run: npm install

    - name: Build admin
      working-directory: ./admin
      run: npm run build
